### PR TITLE
Report reason for skipped test

### LINKED ISSUE #54: Skipped tests don't give skipped reason
If you skip or ignore a test, any information in the skipped message is discarded. I would like this information to be displayed in the UI.

I believe I can make the requisite changes to teamcity messages to make this happen.

### PR DESCRIPTION
**Pull request by lewisc**
Updates the message from a skipped test to include the skipped reason.

If the formatting of the message is off please let me know how you want it.

Fixes #54

### CODE REVIEW

**Comment by lewisc** [comment]
The errors have to do with the fact that the old tests verified the message was only skipped.

Was there a reason for having the message not contain the skipped reason?

**Comment by shalupov** [comment]
Thank you for PR!

I do not remember reason, it was a long time ago.
I think if all tests will pass, it'll be ok.

**Comment by shalupov** [comment]
Please fix the message in the test and we'll know more.

**Comment by lewisc** [comment]
I am not certain this is the correct mechanism for doing this, let me test some stuff

**Comment by lewisc** [comment]
This is the best way I can come up with solving this problem, unfortunately the UI doesn't seem to have a place for ignored information like errors do. This shows up next to the test case, not beneath.

**Comment by shalupov** [comment]
Yes, there is no place for details now. Thanks for tests.

**Pull request merged**
