### PR TITLE
Include captured logging in test standard output.

### PR DESCRIPTION
**Pull request by pavelrad**

### CODE REVIEW

**Comment by pavelrad** [comment]
Hm, something wrong with integration tests. But I can't understand what the problem is. Could you please take a look at the proposed change?

**Comment by shalupov** [comment]
How your code is supposed to work in absence of captured logging?

**Comment by shalupov** [comment]
Anyway, please add integration test about captured logging

**Comment by pavelrad** [comment]
I see, this update can't be so simple :) I'll look at it closer.

**Pull request closed without merging**
